### ISSUE TITLE
Custom preprocessors are ignored by the SqlDatabase upgrade engine

### ISSUE THREAD

**Issue by Mark-Robinson** [DbUp/DbUp#152]
I have created a custom preprocessor and have configured the the UpgradeEngine to use it:
                var upgrader =
                    DeployChanges.To
                        .SqlDatabase(connectionString)
                        .WithScriptsFromFileSystem(upgradeFolder)
                        .WithPreprocessor(new MyCustomVariableSubstitutionPreprocessor())
                        .WithVariable("XmlDocsDirectory", Path.Combine(Directory.GetParent(upgradeFolder).ToString(), @"XML"))
                        .WithScripts()
                        .LogToConsole()
                        .Build();

The custom preprocessor is instantiated but then not used. Instead (according to the stack trace) the default preprocessor is used:

System.InvalidOperationException: Variable 2a has no value defined
   at DbUp.Engine.Preprocessors.VariableSubstitutionPreprocessor.ReplaceToken(Match match, IDictionary`2 variables) in C:\projects\dbup\src\DbUp\Engine\Preprocessors\VariableSubstitutionPreprocessor.cs:line 38
   at DbUp.Engine.Preprocessors.VariableSubstitutionPreprocessor.<Process>b__3_0(Match match) in C:\projects\dbup\src\DbUp\Engine\Preprocessors\VariableSubstitutionPreprocessor.cs:line 31
   at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at DbUp.Engine.Preprocessors.VariableSubstitutionPreprocessor.Process(String contents) in C:\projects\dbup\src\DbUp\Engine\Preprocessors\VariableSubstitutionPreprocessor.cs:line 31
   at DbUp.Support.SqlServer.SqlScriptExecutor.Execute(SqlScript script, IDictionary`2 variables) in C:\projects\dbup\src\DbUp\Support\SqlServer\SqlScriptExecutor.cs:line 97
   at DbUp.Engine.UpgradeEngine.PerformUpgrade() in C:\projects\dbup\src\DbUp\Engine\UpgradeEngine.cs:line 71

(FYI - the error about Variable 2a is due to an encrypted string having the characters ...$2a$... in it which causes the error. Therefore, I want to create my own preprocessor so I can create a different variable syntax (e.g. $$(myVariable)$$) to get around this problem).

I think the issue is being caused by this line in the SqlScriptExecutor class which always seems to use the VariableSubstitutionPreprocessor rather than the supplied custom preprocessor.

            if (variablesEnabled())
                contents = new VariableSubstitutionPreprocessor(variables).Process(contents);

**Comment by Mark-Robinson** [comment]
My mistake. I didn't realise you can call WithVariablesDisabled to disable the default preprocessor and still specify a custom preprocessor. For example, this works:

         var upgrader =
                    DeployChanges.To
                        .SqlDatabase(targetConnectionString)
                        .WithScriptsFromFileSystem(upgradeFolder)
                        .WithVariablesDisabled()
                        .WithPreprocessor(new MyCustomVariableSubstitutionPreprocessor(variableDictionary))
                        .WithScripts()
                        .LogToConsole()
                        .Build();
