### ISSUE TITLE
Cannot run on Postgres 4.0.0-beta0003

### ISSUE THREAD

**Issue by EvgenyKhaliper** [DbUp/DbUp#292]
Following how to at: http://dbup.readthedocs.io/en/latest/
Getting exception below after running 4.0.0-beta0003 on Ubuntu 16.04 + dotnet core 2.0.3

```
System.MissingMethodException: Method not found: 'System.String Npgsql.NpgsqlException.get_Line()'.
   at DbUp.Postgresql.PostgresqlScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action excuteCommand)
   at DbUp.Support.ScriptExecutor.<>c__DisplayClass18_0.<Execute>b__0(Func`1 dbCommandFactory)
   at DbUp.Engine.Transactions.NoTransactionStrategy.Execute(Action`1 action)
   at DbUp.Engine.Transactions.DatabaseConnectionManager.ExecuteCommandsWithManagedConnection(Action`1 action)
   at DbUp.Support.ScriptExecutor.Execute(SqlScript script, IDictionary`2 variables)
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()
```

Any ideas ?

**Comment by droyad** [comment]
What version of `Npgsql` is restored in your project and is it a version that is compatible with the one DbUp  references (`2.2.1`)?

**Comment by EvgenyKhaliper** [comment]
Yeah, now i know that. 
Thanks
