### ISSUE TITLE
Upgrade HTML report fails to generate if code-based scripts are found

### ISSUE THREAD

**Issue by Waldo000000** [DbUp/DbUp#387]
**Repro**

1. Add a new code-based migration to your assembly (e.g. [this sample one](https://github.com/DbUp/DbUp/blob/master/src/Samples/SampleApplication/Scripts/Script0005%20-%20ComplexUpdate.cs))
2. Run `GenerateUpgradeHtmlReport` as shown [in this example](https://github.com/DbUp/DbUp/blob/master/docs/more-info/html-report.md), but replace `WithScriptsEmbeddedInAssembly` with `WithScriptsAndCodeEmbeddedInAssembly`

**Expected**: Report is generated (presumably just showing that a code-based script will be run)
**Actual**:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=ExecuteReader requires an open and available Connection. The connection's current state is closed.
  Source=System.Data.SqlClient
  StackTrace:
   at System.Data.SqlClient.SqlCommand.ValidateCommand(Boolean async, String method)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at Octofront.Core.UpgradeScripts.Script0042.ProvideScript(Func`1 commandFactory) in C:\code\OctopusDeploy\Octofront\source\Octofront.Core\UpgradeScripts\Script0042.cs:line 29
```

**Comment by droyad** [comment]
As far as I can tell the original intention for the "code based" migrations was just to return a SQL script. However it's commonly used to run SQL right in the ProvideScript method. So, I think this is too hard to fix until there is first class support for code based migrations.

**Comment by Waldo000000** [comment]
Right, that's interesting. So even though [the doco](https://dbup.readthedocs.io/en/latest/usage/#code-based-scripts) says:

>Of course, the command factory can be used for more than just queries. The entire migration itself can be performed in code.

...the `return ""` in the example does make it smell like a bit of an afterthought.
