### ISSUE TITLE
Creating Server Agent jobs

### ISSUE THREAD

**Issue by jorismathijssen** [DbUp/DbUp#405]
Hello, i was wondering if its possible to create Jobs in the server agent.

I have a script that uses msdb.dbo.sp_add_job to create the job but i get a weird error.

> Script block number: 1; Message: Invalid object name 'SchemaVersions'.
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'SchemaVersions'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

Got my example script here:
https://gist.github.com/jorismathijssen/da52a8f75badfa584656732a6e1ce00d

**Comment by jorismathijssen** [comment]
Solution not found but problem is gone after i moved my scripts.
