### ISSUE TITLE
VSTS support

### ISSUE THREAD

**Issue by jorismathijssen** [DbUp/DbUp#406]
Hello here,

I'm trying to combine DbUp with my VSTS auto deploy. Does someone have any suggestions? Is there a way to run the console app i created in VSTS so my migrations is executed in the deploy.

I'm looking forward to any ideas.

**Comment by jorismathijssen** [comment]
Hi @wazbekker 

This sounds so easy, but still i didn't think about it this way. I will try this out but it sounds like this will work.

Thanks you for the information!

**Comment by jorismathijssen** [comment]
@wazbekker i have a small follow up question. My DBUP application is throwing a exception but the task is not failing. One example is the exception below. I know how to solve the exception but i think its weird that the task is successful. 

Maybe its something in my console app or in my powershell script?

> System.Data.SqlClient.SqlException (0x80131904): Cannot find the object "dbo.savedroute" because it does not exist or you do not have permissions.
2019-04-26T08:30:47.3090421Z    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2019-04-26T08:30:47.3090657Z    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
2019-04-26T08:30:47.3090925Z    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
2019-04-26T08:30:47.3091193Z    at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
2019-04-26T08:30:47.3091449Z    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
2019-04-26T08:30:47.3091654Z    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
2019-04-26T08:30:47.3091847Z    at DbUp.Support.ScriptExecutor.ExecuteNonQuery(IDbCommand command)
2019-04-26T08:30:47.3092059Z    at DbUp.SqlServer.SqlScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action excuteCommand)
2019-04-26T08:30:47.3092264Z ClientConnectionId:97acbf93-8365-421f-be50-f33b2875660d
2019-04-26T08:30:47.3092426Z Error Number:4902,State:1,Class:16

**Comment by AdrianJSClark** [comment]
@jorismathijssen I'm not sure how your script operates, but by default the last exit code returned will be checked and if it is non-zero it will fail the step. You'll need to make sure you catch exceptions in your console app and return a non-zero code when there's an exception.

You can also fail the step by writing to `stderr` if you set an option on the step.

The PowerShell step documentation is here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops

**Comment by wazbekker** [comment]
@jorismathijssen this is the way I did it in my Power shell script.

`#2>&1 redirects standard error (the 2) to the same place as standard output (the 1)
$output = C:\DbUpdate\Database.Update.exe 2>&1

$errorText = @()

for ($i=0; $i -lt $output.length; $i++) {
    $value = $output[$i]

    Write "$value`r"

    $errorText += "$value`r"

    if($value.Contains("OracleException") -or $value.Contains("ORA-"))
    {      
	    throw $errorText
    }    
}`
