### ISSUE TITLE
Random Sql Exceptions with Incorrect syntax near '?' in SQL files (0x80131904)

### ISSUE THREAD

**Issue by haroonyoeu** [DbUp/DbUp#457]
I'm looking at implementing DbUp in an existing project with stored procs, views and functions that have drop and create statements. Unfortunately some run fine while others run into the exception "SqlException (0x80131904): Incorrect syntax near '?'" and I can't find where the issue is in the script. These scripts run fine as-is when executing in SSMS against MSSQL.

Its very odd because some SQL file scripts will drop / create just fine, however others will fail on various places such as parameter inputs or at inner joins. For example, the below script in sp_test123.sql, if I comment out all of the INNER JOINs the script will run just fine. I've combed through the documentation, however haven't been able to find if I'm missing a configuration option. Thus far none of our migration scripts have not run into this issue.

sp_test123.sql:
```sql
CREATE OR ALTER PROCEDURE sp_test123    
	@State nvarchar(50),  
	@City nvarchar(30)  
AS  
BEGIN  
	SELECT [CustomerID]  
FROM   
(  
SELECT DISTINCT c.[CustomerID]  
FROM [SalesLT].[Customer] c  
INNER JOIN [SalesLT].[CustomerAddress] ca ON ca.[CustomerID] = c.[CustomerID]  
--INNER JOIN [SalesLT].[Address] a ON a.[AddressID] = ca.[AddressID]  
-- WHERE j.State = @State   
) AS T  
END  
GO
```

Program.cs excerpt:
```csharp
var upgrader = DeployChanges.To
.SqlDatabase(connectionString)
.WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly(), s => s.StartsWith("ConsoleApp1.Scripts.", StringComparison.OrdinalIgnoreCase))
.LogToConsole()
.JournalToSqlTable("dbo", "SchemaVersions")
.WithTransaction()
.Build();

var storedProcUpgrader = DeployChanges.To
.SqlDatabase(connectionString)
.WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly(), s => s.StartsWith("ConsoleApp1.AlwaysRun.", StringComparison.OrdinalIgnoreCase))
.LogToConsole()
.JournalTo(new NullJournal())
.WithTransaction()
.Build();
```

Console Log:
```powershell
Beginning transaction
Beginning database upgrade
Checking whether journal table exists..
Fetching list of already executed scripts.
No new scripts need to be executed - completing.
Beginning transaction
Beginning database upgrade
Executing Database Server script 'ConsoleApp1.AlwaysRun.SQLQuery3.sql'
SQL exception has occured in script: 'ConsoleApp1.AlwaysRun.SQLQuery3.sql'
Script block number: 0; Block line 10; Message: sp_test123
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '?'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DbUp.Support.ScriptExecutor.ExecuteNonQuery(IDbCommand command)
   at DbUp.Support.ScriptExecutor.<>c__DisplayClass18_2.<Execute>b__1()
   at DbUp.SqlServer.SqlScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action excuteCommand)
ClientConnectionId:7e325b28-f5eb-448e-868f-c07d3a39efb7
Error Number:102,State:1,Class:15
DB exception has occured in script: 'ConsoleApp1.AlwaysRun.SQLQuery3.sql'
Script block number: 0; Message: Incorrect syntax near '?'.
   at System.Data.SqlClient.SqlConnection.OnError( ...
```

packages.config

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="dbup" version="4.2.0" targetFramework="net471" />
  <package id="dbup-core" version="4.2.0" targetFramework="net471" />
  <package id="dbup-sqlserver" version="4.2.0" targetFramework="net471" />
</packages>
```

Sample connstring for MSSQL 14.0.1000.169
```config
connectionString="Server=localhost\sqlexpress;Database=AdventureWorksLT2017;Trusted_connection=true"
```

**Comment by blueelvis** [comment]
@haroonyoeu - I just faced this issue with DbUp as well. Turns out there were indeed invalid characters (In particular Spaces) which Visual Studio and SSMS didn't highlight and also the file was saved in ANSI format.
I used the instructions over here to find those invalid characters and fix them - https://stackoverflow.com/a/23705696/2758198

After fixing the script, it worked.

**Comment by sungam3r** [comment]
Thanks @blueelvis . Closed as answered.
