### ISSUE TITLE
This NpgsqlTransaction has completed; it is no longer usable.

### ISSUE THREAD

**Issue by AnthonyMastrean** [DbUp/DbUp#493]
I have a pretty simple migration project. All of the migration scripts are embedded in this project. It used to work, until I added the `WithTransaction` option.

```
        static int Main(string[] args)
        {
            var engine = DeployChanges.To
                .PostgresqlDatabase(conf.GetConnectionString("Database"))
                .WithTransaction()
                .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly())
                .LogToConsole()
                .Build();
            
            var result = engine.PerformUpgrade();

            if (!result.Successful)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.Error.WriteLine(result.Error);
                Console.ResetColor();
#if DEBUG
                Console.ReadLine();
#endif
                return -1;
            }

            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("Success!");
            Console.ResetColor();

            return 0;
        }
```

According to the console output, the scripts run, the journal table is created, I get a success message, then I get an Npgsql transaction exception.

```
$ dotnet run -p src/Migration
Beginning transaction
Beginning database upgrade
Checking whether journal table exists..
Journal table does not exist
Executing Database Server script 'Migration.Scripts.20190226151710.sql'
Checking whether journal table exists..
Creating the "schemaversions" table
The "schemaversions" table has been created
Executing Database Server script 'Migration.Scripts.20190226151711.sql'
...
Executing Database Server script 'Migration.Scripts.20200121120258.sql'
Upgrade successful
Upgrade failed due to an unexpected exception:
System.InvalidOperationException: This NpgsqlTransaction has completed; it is no longer usable.
   at Npgsql.NpgsqlTransaction.CheckCompleted() in C:\projects\npgsql\src\Npgsql\NpgsqlTransaction.cs:line 378
   at Npgsql.NpgsqlTransaction.Commit(Boolean async) in C:\projects\npgsql\src\Npgsql\NpgsqlTransaction.cs:line 118
   at Npgsql.NpgsqlTransaction.Commit() in C:\projects\npgsql\src\Npgsql\NpgsqlTransaction.cs:line 112
   at DbUp.Engine.Transactions.SingleTransactionStrategy.Dispose()
   at DbUp.Engine.Transactions.DatabaseConnectionManager.<OperationStarting>b__7_0()
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()
System.InvalidOperationException: This NpgsqlTransaction has completed; it is no longer usable.
   at Npgsql.NpgsqlTransaction.CheckCompleted() in C:\projects\npgsql\src\Npgsql\NpgsqlTransaction.cs:line 378
   at Npgsql.NpgsqlTransaction.Commit(Boolean async) in C:\projects\npgsql\src\Npgsql\NpgsqlTransaction.cs:line 118
   at Npgsql.NpgsqlTransaction.Commit() in C:\projects\npgsql\src\Npgsql\NpgsqlTransaction.cs:line 112
   at DbUp.Engine.Transactions.SingleTransactionStrategy.Dispose()
   at DbUp.Engine.Transactions.DatabaseConnectionManager.<OperationStarting>b__7_0()
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()
```

**Comment by AnthonyMastrean** [comment]
Uh-oh, someone on my team wrote a migration script with explicit BEGIN/COMMIT statements... I guess that worked when I was running without a transaction (essentially, [AUTOCOMMIT ON](https://www.postgresql.org/docs/current/ecpg-sql-set-autocommit.html)), but PostgreSQL doesn't allow nested transactions, so those statements ended the DbUp-created transaction!
