### ISSUE TITLE
Upgrade fails after MS SQL Db creation in version 4.3.0

### ISSUE THREAD

**Issue by flexoft-sk** [DbUp/DbUp#500]
Hi,
I’m using DbUp with my locally installed MS SQL 2016 Standard Edition. When the db doesn’t exist DbUp creates it, but creation of tables fails with

> System.Data.SqlClient.SqlException (0x80131904): Cannot open database " TestDb" requested by the login. The login failed.
Login failed for user '…'.

After second start of the app schema is updated.

When I downgrade to 4.2.0 everything works fine, no need to restart the application second time.

My Connection String looks like this:

`Server=myMachine\\ST2016;Database=TestDb;User ID=;Password=;ConnectRetryCount=0;Integrated Security=True`

 

My code looks like this:

```EnsureDatabase.For.SqlDatabase(connectionString);
var upgrader =
         DeployChanges.To
        .SqlDatabase(connectionString)
        .WithTransaction()
        .WithScriptsFromFileSystem(scriptFolderPath)
        .LogTo(new UpgradeLogger(_logger))
        .Build();
var result = upgrader.PerformUpgrade();

**Comment by PhilG112** [comment]
Also having this issue with DbUp version `4.3.0` but not with version `4.2.0`. Using sql server 2019 dev on Ubuntu 20.04

Connection string in my config: `Server=localhost;Database=Astro;User Id=SA;Password=;`

Code:
```cs
var connString = config.GetConnectionString("Astro");

EnsureDatabase.For.SqlDatabase(connString);

var upgrader = DeployChanges
    .To
    .SqlDatabase(connString)
    .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly())
    .LogToConsole()
    .Build();
```

Running the app the first time produces:
```
Master ConnectionString => Data Source=localhost;Initial Catalog=master;User ID=SA;Password=**********
Database not found on server with connection string in settings: Cannot open database "Astro" requested by the login. The login failed.
Login failed for user 'sa'.
Created database Astro
Upgrade failed due to an unexpected exception:
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "Astro" requested by the login. The login failed.
Login failed for user 'sa'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at DbUp.Engine.Transactions.DatabaseConnectionManager.OperationStarting(IUpgradeLog upgradeLog, List`1 executedScripts)
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()
ClientConnectionId:e7ade2cc-bca0-46d2-bc00-54c03fee272c
Error Number:4060,State:1,Class:11
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "Astro" requested by the login. The login failed.
Login failed for user 'sa'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at DbUp.Engine.Transactions.DatabaseConnectionManager.OperationStarting(IUpgradeLog upgradeLog, List`1 executedScripts)
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()
ClientConnectionId:e7ade2cc-bca0-46d2-bc00-54c03fee272c
Error Number:4060,State:1,Class:11
```

Running the app right after the first then produces result:
```
Master ConnectionString => Data Source=localhost;Initial Catalog=master;User ID=SA;Password=**********
Beginning database upgrade
Checking whether journal table exists..
Journal table does not exist
Executing Database Server script 'Astro.DbUp.Scripts.Script001 - Initial Schema.sql'
Checking whether journal table exists..
Creating the [SchemaVersions] table
The [SchemaVersions] table has been created
Upgrade successful
Success!
```

**Comment by mjauernig** [comment]
Note: Write documentation how to use "mssql" with auto creation of database.
