### ISSUE TITLE
Authentication error 

### ISSUE THREAD

**Issue by miguelcjalmeida** [DbUp/DbUp#545]
Hello,

I am getting an authentication error when executing the ```upgrader.PerformUpgrade();```. I believe the issue is related to using an old postgree driver, which do not supports authentication by "scram-sha-256".

These are my database and nuget dependencies versions:

Postgres Version: 13
```
<PackageReference Include="DbUp" Version="4.5.0" />
<PackageReference Include="dbup-postgresql" Version="4.5.0" />
```

Here it is the error thrown:

```
System.NotSupportedException: Authentication method not supported (Received: 10)
   at Npgsql.NpgsqlConnector.ParseServerMessage(ReadBuffer buf, BackendMessageCode code, Int32 len, DataRowLoadingMode dataRowLoadingMode, Boolean 
isPrependedMessage)
   at Npgsql.NpgsqlConnector.DoReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications)
   at Npgsql.NpgsqlConnector.ReadExpecting[T](Boolean async)
   at Npgsql.NpgsqlConnector.Authenticate(String username, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.Open(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.Open()
   at DbUp.Engine.Transactions.DatabaseConnectionManager.OperationStarting(IUpgradeLog upgradeLog, List`1 executedScripts)
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()
System.NotSupportedException: Authentication method not supported (Received: 10)
   at Npgsql.NpgsqlConnector.ParseServerMessage(ReadBuffer buf, BackendMessageCode code, Int32 len, DataRowLoadingMode dataRowLoadingMode, Boolean 
isPrependedMessage)
   at Npgsql.NpgsqlConnector.DoReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications)
   at Npgsql.NpgsqlConnector.ReadExpecting[T](Boolean async)
   at Npgsql.NpgsqlConnector.Authenticate(String username, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.Open(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.Open()
   at DbUp.Engine.Transactions.DatabaseConnectionManager.OperationStarting(IUpgradeLog upgradeLog, List`1 executedScripts)
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()
```

Downgrading my postgres password encryption to MD5 is a workaround, but not recommended alternative. 

You could check the database encryption type by running: 
```
postgres=# show password_encryption;
 password_encryption
---------------------
 scram-sha-256
(1 row)
```

Not sure if this is going to help, but here is the code I am running:

```
var connectionString = "Host=localhost;Port=5432;Database=mydb;Username=postgres;Password=dbupisgreat";

var upgrader =
    DeployChanges.To
        .PostgresqlDatabase(connectionString)
        .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly())
        .LogToConsole()
        .Build();

var result = upgrader.PerformUpgrade();
```

**Comment by TroyJoachim** [comment]
I solved this by upgrading my Npgsql package to the latest version.

**Comment by belczyk** [comment]
I had exactly the same issue in an empty console app (I added only dbup-core 4.5 and dbup-postgresql 4.5). 
I've added Npgsql 5.0.3 package and it solved this issue.

**Comment by Arrow7000** [comment]
I can report the same. Adding Npgsql fixed this for me.

**Comment by seanamos** [comment]
This is because of Nuget's unique, long standing and honestly incorrect behavior of getting the lowest compatible version of transitive dependencies.

`dbup-postgresql` specifies its dependency on Npgsql as `>=3.2.6`. Nuget will then grab Npgsql 3.2.6. You either need to use the explicit dependency behavior option "Highest" in VS (which they removed...), or add a newer version Npgsql directly to your project.

**Comment by huesie** [comment]
I've verified that this is fixed by minor upgrade of Npgsql from v3.2.6→3.2.7 - I'll raise a PR and include this bug - thanks to all who added so much great info.

**Comment by jeremysimmons** [comment]
this also worked for me. my aws lightsail PostgreSQL database (12.8) where the old version worked fine.
I installed PostgreSQL 14.1 locally and it failed.
Upgrading the nuget package fixed my issue.

**Comment by MhmdAbdo74** [comment]
how you make it can you give me more details or steps
