### ISSUE TITLE
OracleDatabaseWithDefaultDelimiter not breaking the script on /

### ISSUE THREAD

**Issue by beppler** [DbUp/DbUp#569]
I'm using the version 4.5.0 of DbUp with Oracle.

Running the following code I was expecting that 4 commands would be sent to oracle from the migration bellow:

Code:
```c#
var builder = DeployChanges.To
    .OracleDatabaseWithDefaultDelimiter(connectionString)
    .JournalToOracleTable("AuthSchemaVersions")
    .WithTransactionPerScript()
    .WithScriptsEmbeddedInAssembly(typeof(Program).Assembly, name => name.StartsWith(migrationsFilter))
    .WithVariable("ApplicationUser", applicationUser)
    .LogToConsole()
    .LogScriptOutput();

result = upgrader.PerformUpgrade();

if (!result.Successful)
{
    Console.WriteLine("Error script:");
    Console.WriteLine(result.ErrorScript.Contents);
    return 1;
}
```

Migration:
```sql
CREATE TABLE PersistedGrants
(
    Key VARCHAR2(255) NOT NULL,
    Type VARCHAR2(64) NOT NULL,
    SubjectId VARCHAR2(255) NOT NULL,
    ClientId VARCHAR2(255) NOT NULL,
    CreationTime DATE NOT NULL,
    Expiration DATE NULL,
    Data CLOB NOT NULL
);
/
ALTER TABLE PersistedGrants
ADD CONSTRAINT PK_PersistedGrants
PRIMARY KEY (Key);
/
CREATE INDEX IX_PersistedGrants_SCT ON PersistedGrants (SubjectId, ClientId, Type);
/
GRANT SELECT,INSERT,UPDATE,DELETE ON PersistedGrants TO $ApplicationUser$;
```

But I'm getting an error from Oracle and the ErrorScript contents are showing the complete script like bellow:

```
Beginning database upgrade
Checking whether journal table exists..
Journal table does not exist
Executing Database Server script 'MPS.Libertas.Auth.Migrator.Migrations.Oracle.201812040839_PersistedGrants.sql'
Checking whether journal table exists..
Creating the "AuthSchemaVersions" table
The "AuthSchemaVersions" table has been created
Oracle exception has occured in script: 'MPS.Libertas.Auth.Migrator.Migrations.Oracle.201812040839_PersistedGrants.sql'
Oracle error code: 0; Number -2147467259; Message: 922
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00922: opção não encontrada ou inválida
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at DbUp.Support.ScriptExecutor.ExecuteAndLogOutput(IDbCommand command)
   at DbUp.Oracle.OracleScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action executeCommand)
DB exception has occured in script: 'MPS.Libertas.Auth.Migrator.Migrations.Oracle.201812040839_PersistedGrants.sql'
Script block number: 0; Message: ORA-00922: opção não encontrada ou inválida
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00922: opção não encontrada ou inválida
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at DbUp.Support.ScriptExecutor.ExecuteAndLogOutput(IDbCommand command)
   at DbUp.Oracle.OracleScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action executeCommand)
   at DbUp.Support.ScriptExecutor.<>c__DisplayClass18_0.<Execute>b__0(Func`1 dbCommandFactory)
   at DbUp.Support.ScriptExecutor.Execute(SqlScript script, IDictionary`2 variables)
Upgrade failed due to an unexpected exception:
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00922: opção não encontrada ou inválida
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at DbUp.Support.ScriptExecutor.ExecuteAndLogOutput(IDbCommand command)
   at DbUp.Oracle.OracleScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action executeCommand)
   at DbUp.Support.ScriptExecutor.<>c__DisplayClass18_0.<Execute>b__0(Func`1 dbCommandFactory)
   at DbUp.Support.ScriptExecutor.Execute(SqlScript script, IDictionary`2 variables)
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()
Error script:
CREATE TABLE PersistedGrants
(
    Key VARCHAR2(255) NOT NULL,
    Type VARCHAR2(64) NOT NULL,
    SubjectId VARCHAR2(255) NOT NULL,
    ClientId VARCHAR2(255) NOT NULL,
    CreationTime DATE NOT NULL,
    Expiration DATE NULL,
    Data CLOB NOT NULL
);
/
ALTER TABLE PersistedGrants
ADD CONSTRAINT PK_PersistedGrants
PRIMARY KEY (Key);
/
CREATE INDEX IX_PersistedGrants_SCT ON PersistedGrants (SubjectId, ClientId, Type);
/
GRANT SELECT,INSERT,UPDATE,DELETE ON PersistedGrants TO $ApplicationUser$;
```

I appears that the script are not being broken on the separator.

PS: If I remove the / on script and change to use OracleDatabaseWithSemicolonDelimiter the script runs fine.

**Comment by beppler** [comment]
Forget, the problem is that using the ; as delimiter removes it from command and using / (as the ; goes to oracle with the script) is causing a syntax error.
The splitter is working well, to test I created the classes bellow:
```c#
    public class MyOracleDatabaseConnectionManager : DatabaseConnectionManager
    {
        private readonly OracleCommandSplitter splitter;

        public MyOracleDatabaseConnectionManager(string connectionString, char delimiter) : base(l => new OracleConnection(connectionString))
        {
            splitter = new OracleCommandSplitter(delimiter);
        }

        public override IEnumerable<string> SplitScriptIntoCommands(string scriptContents)
        {
            var commands = splitter.SplitScriptIntoCommands(scriptContents);
            return commands;
        }
    }

    public static class MyOracleDatabaseExtensions
    {
        public static UpgradeEngineBuilder MyOracleDatabase(this SupportedDatabases supported, string connectionString, char delimiter, string journalTable)
        {
            var builder = new UpgradeEngineBuilder();
            builder.Configure(c => c.ConnectionManager = new MyOracleDatabaseConnectionManager(connectionString, delimiter));
            builder.Configure(c => c.ScriptExecutor = new OracleScriptExecutor(() => c.ConnectionManager, () => c.Log, null, () => c.VariablesEnabled, c.ScriptPreprocessors, () => c.Journal));
            builder.Configure(c => c.Journal = new OracleTableJournal(() => c.ConnectionManager, () => c.Log, null, journalTable));
            builder.WithPreprocessor(new OraclePreprocessor());
            return builder;
        }
    }
```
