### ISSUE TITLE
Can't figure how to execute Oracle scripts

### ISSUE THREAD

**Issue by sylvainonweb** [DbUp/DbUp#574]
I see that with Oracle, I need to use the / delimiter so I configure DbUp like this.

```
  var scriptsExecutor =
                DeployChanges.To
                    .OracleDatabase(connectionString, null, "/")
                    .WithScriptsFromFileSystem("Scripts", new FileSystemScriptOptions
                    {
                        IncludeSubDirectories = true
                    })
                    .LogToConsole()
                    .JournalTo(new NullJournal())
                    .Build();

            var result = scriptsExecutor.PerformUpgrade();
```

In the Scripts folder, I put a sql file containing :
```
UPDATE CONFIGURATION SET DATABASE_VERSION = '4.0';
/

DECLARE
    nextSequence NUMBER(10,0);
BEGIN
    nextSequence := SERVICE_SEQ.NEXTVAL;

    INSERT INTO SERVICE(ID, LIBELLE) VALUES(nextSequence, 'Service 3');
END;
/
```
=> the following error occurs : 

```
Oracle error code: 1; Number -2147467259; Message: 900
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00900: invalid SQL statement
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at DbUp.Support.ScriptExecutor.ExecuteNonQuery(IDbCommand command) in C:\Users\sylvain.blanchard\Source\Repos\DbUp\src\dbup-core\Support\ScriptExecutor.cs:line 173
   at DbUp.Support.ScriptExecutor.<>c__DisplayClass18_2.<Execute>b__1() in C:\Users\sylvain.blanchard\Source\Repos\DbUp\src\dbup-core\Support\ScriptExecutor.cs:line 146
   at DbUp.Oracle.OracleScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action executeCommand) in C:\Users\sylvain.blanchard\Source\Repos\DbUp\src\dbup-oracle\OracleScriptExecutor.cs:line 47
```

I also tried to remove the ; on the single statement like this
```
UPDATE CONFIGURATION SET DATABASE_VERSION = '4.0'
/

DECLARE nextSequence NUMBER(10,0);
BEGIN
    nextSequence := SERVICE_SEQ.NEXTVAL;
    INSERT INTO SERVICE(ID, LIBELLE) VALUES(nextSequence, 'Service 3');
END;
/
```

but the folloging error occurs
```
Oracle error code: 0; Number -2147467259; Message: 933
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00933: SQL command not properly ended
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at DbUp.Support.ScriptExecutor.ExecuteNonQuery(IDbCommand command) in C:\Users\sylvain.blanchard\Source\Repos\DbUp\src\dbup-core\Support\ScriptExecutor.cs:line 173
   at DbUp.Support.ScriptExecutor.<>c__DisplayClass18_2.<Execute>b__1() in C:\Users\sylvain.blanchard\Source\Repos\DbUp\src\dbup-core\Support\ScriptExecutor.cs:line 146
   at DbUp.Oracle.OracleScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action executeCommand) in C:\Users\sylvain.blanchard\Source\Repos\DbUp\src\dbup-oracle\OracleScriptExecutor.cs:line 47
```

Can you help me ?

**Comment by phenixita** [comment]
Hi @sylvainonweb I'm facing issues with Oracle too. In particular can you show me an example of the connection string you are using?
I tried with many formats but without success! I see that you can execute the scripts...

**Comment by sylvainonweb** [comment]
Hi @phenixita, the connection string I use has the following format

`var connectionString = $"Data Source={DATASOURCE};User Id={USER_ID};Password={PASSWORD};Pooling=false;Connection Timeout=0";`

**Comment by phenixita** [comment]
> Hi @phenixita, the connection string I use has the following format
> 
> `var connectionString = $"Data Source={DATASOURCE};User Id={USER_ID};Password={PASSWORD};Pooling=false;Connection Timeout=0";`

Thanks it works!

**Comment by sungam3r** [comment]
Closed due inactivity.
