### ISSUE TITLE
Get exact line number of SQL error

### ISSUE THREAD

**Issue by egokick** [DbUp/DbUp#609]
I'm running DbUp with MySql, I'd like to output the exact line number a script fails on to help with debugging. Is it possible to do this? Pasted what I'm logging out at the moment, I can see the "script block" but would prefer to include the exact line number, and if possible the actual sql statement that failed (not the entire file).

MySql exception has occured in script: '0000237-scriptname.sql'
Script block number: 3; MySql error code: 0; Number 1138; Message: Invalid use of NULL value
MySql.Data.MySqlClient.MySqlException (0x80004005): Invalid use of NULL value
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at DbUp.Support.ScriptExecutor.ExecuteNonQuery(IDbCommand command)
   at DbUp.MySql.MySqlScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action executeCommand)

**Comment by programcsharp** [comment]
As far as I know, this isn't currently possible but it would be very good for debugging.

I'd actually like to be able to echo the script to the log as it executes, and capture the response from MySql coming back -- "50 rows updated" etc.

**Comment by ScotMeyer** [comment]
In the example from https://dbup.readthedocs.io/en/latest/
```...
  if (!result.Successful)
    {
        Console.ForegroundColor = ConsoleColor.Red;
        Console.WriteLine(result.Error);
        Console.ResetColor();
#if DEBUG
        Console.ReadLine();
#endif                
        return -1;
    }
```
 You could do 
```
...
Console.WriteLine(result.Error);
Console.WriteLine(result.ErrorScript.Name);
Console.WriteLine(result.Error.Message);
```
to help identify the exact script that failed, and the message returned from the SQL Database during execution.
