### ISSUE TITLE
EnsureDatabase for Azure SQL error

### ISSUE THREAD

**Issue by mrbit10** [DbUp/DbUp#614]
latest ver v4.5.0

using:

EnsureDatabase.For.SqlDatabase(connectionString, 300, AzureDatabaseEdition.Basic);

This exception is thrown:
```
System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Incorrect syntax near 'basic'.
  Source=Core .Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at SqlServerExtensions.SqlDatabase(SupportedDatabasesForEnsureDatabase supported, String connectionString, IUpgradeLog logger, Int32 timeout, AzureDatabaseEdition azureDatabaseEdition, String collation)
   at SqlServerExtensions.SqlDatabase(SupportedDatabasesForEnsureDatabase supported, String connectionString, Int32 commandTimeout, AzureDatabaseEdition azureDatabaseEdition)
   at DbUp.Program.RunOptionsAndReturnExitCode(Options o, ILogger logger) in C:\projects\elwynn v1\db-scripts\dbUp\Program.cs:line 81
```

**Comment by mrbit10** [comment]
here is the output:

`CommandText "create database [dbUpTest] ( EDITION = ''basic'' );"`


if i were to write that statement in SQL i would write it this way

`CREATE DATABASE dbUpTtest ( EDITION = 'basic' ) ;`

^^ this works, I think double single quote is causing the problem?

when executed to SQL directly: 
```
Msg 102, Level 15, State 1, Line 2
Incorrect syntax near 'basic'.

Completion time: 2022-05-02T16:08:35.3054115-05:00
```

**Comment by SEAHood** [comment]
Can confirm it's the double single quote causing the problem - any updates on this?
