### ISSUE TITLE
SQL exception logged 3 times

### ISSUE THREAD

**Issue by stevendarby** [DbUp/DbUp#650]
If a script fails and sql client throws an exception, with LogToConsole enabled I see the exception output 3 times:

```
SQL exception has occured in script: 'XXX.sql'
Script block number: 0; Block line 2; Procedure ; Number 2714; Message: YYY
<STACKTRACE>
DB exception has occured in script: 'XXX.sql'
Script block number: 0; Message: YYY
<STACKTRACE>
Error occured when executing scripts, transaction will be rolled back
Upgrade failed due to an unexpected exception:
<STACKTRACE>
```

Looking at the code it looks like this is because these three classes which execute the scripts all catch, log and throw again for the next one to do the same.

https://github.com/DbUp/DbUp/blob/master/src/dbup-sqlserver/SqlScriptExecutor.cs
https://github.com/DbUp/DbUp/blob/master/src/dbup-core/Support/ScriptExecutor.cs
https://github.com/DbUp/DbUp/blob/master/src/dbup-core/Engine/UpgradeEngine.cs

I don't want to disable logging to console because there is other useful output, but I don't want it to log errors three times. Consider logging just once or, given the exception is returned in the `DatabaseUpgradeResult`, not at all, so the application can decide.

**Comment by stevendarby** [comment]
Any interest in this? Has it been triaged as a valid issue? Are there workarounds?

**Comment by mjauernig** [comment]
I can confirm this bug. With the following setup

``` 
UpgradeEngine upgradeEngine =
    DeployChanges.To
        .SqlDatabase(ConnectionString)
        .WithScriptsAndCodeEmbeddedInAssembly(Assembly.GetExecutingAssembly())
        .LogToConsole()
        .WithExecutionTimeout(TimeSpan.FromSeconds(180))
        .Build();
```

The error is repeated 3 times. Here is a sample
```
Beginning database upgrade
Checking whether journal table exists..
Fetching list of already executed scripts.
Executing Database Server script 'TestDbUp.Scripts.J2023.S20230801-01-Update.sql'
Checking whether journal table exists..
SQL exception has occured in script: 'TestDbUp.Scripts.J2023.S20230801-01-Update.sql'
Script block number: 3; Block line 2; Procedure ; Number 2627; Message: Verletzung der PRIMARY KEY-Einschränkung "PK_Dataclass". Ein doppelter Schlüssel kann in das dbo.Dataclass-Objekt nicht eingefügt werden. Der doppelte Schlüsselwert ist (90112).
Verletzung der PRIMARY KEY-Einschränkung "PK_Helpertable". Ein doppelter Schlüssel kann in das dbo.Helpertable-Objekt nicht eingefügt werden. Der doppelte Schlüsselwert ist (991).
Die Anweisung wurde beendet.
Die Anweisung wurde beendet.
System.Data.SqlClient.SqlException (0x80131904): Verletzung der PRIMARY KEY-Einschränkung "PK_Dataclass". Ein doppelter Schlüssel kann in das dbo.Dataclass-Objekt nicht eingefügt werden. Der doppelte Schlüsselwert ist (90112).
Verletzung der PRIMARY KEY-Einschränkung "PK_Helpertable". Ein doppelter Schlüssel kann in das dbo.Helpertable-Objekt nicht eingefügt werden. Der doppelte Schlüsselwert ist (991).
Die Anweisung wurde beendet.
Die Anweisung wurde beendet.
   bei System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   bei System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   bei System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   bei System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   bei System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   bei DbUp.Support.ScriptExecutor.ExecuteNonQuery(IDbCommand command) in /_/src/dbup-core/Support/ScriptExecutor.cs:Zeile 173.
   bei DbUp.Support.ScriptExecutor.<>c__DisplayClass18_1.<Execute>b__1() in /_/src/dbup-core/Support/ScriptExecutor.cs:Zeile 146.
   bei DbUp.SqlServer.SqlScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action executeCommand) in /_/src/dbup-sqlserver/SqlScriptExecutor.cs:Zeile 44.
ClientConnectionId:a7a7011f-4ea5-4785-888e-1c42ffa5b709
Fehlernummer (Error Number):2627,Status (State):1,Klasse (Class):14
DB exception has occured in script: 'TestDbUp.Scripts.J2023.S20230801-01-Update.sql'
Script block number: 3; Message: Verletzung der PRIMARY KEY-Einschränkung "PK_Dataclass". Ein doppelter Schlüssel kann in das dbo.Dataclass-Objekt nicht eingefügt werden. Der doppelte Schlüsselwert ist (90112).
Verletzung der PRIMARY KEY-Einschränkung "PK_Helpertable". Ein doppelter Schlüssel kann in das dbo.Helpertable-Objekt nicht eingefügt werden. Der doppelte Schlüsselwert ist (991).
Die Anweisung wurde beendet.
Die Anweisung wurde beendet.
System.Data.SqlClient.SqlException (0x80131904): Verletzung der PRIMARY KEY-Einschränkung "PK_Dataclass". Ein doppelter Schlüssel kann in das dbo.Dataclass-Objekt nicht eingefügt werden. Der doppelte Schlüsselwert ist (90112).
Verletzung der PRIMARY KEY-Einschränkung "PK_Helpertable". Ein doppelter Schlüssel kann in das dbo.Helpertable-Objekt nicht eingefügt werden. Der doppelte Schlüsselwert ist (991).
Die Anweisung wurde beendet.
Die Anweisung wurde beendet.
   bei System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   bei System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   bei System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   bei System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   bei System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   bei DbUp.Support.ScriptExecutor.ExecuteNonQuery(IDbCommand command) in /_/src/dbup-core/Support/ScriptExecutor.cs:Zeile 173.
   bei DbUp.Support.ScriptExecutor.<>c__DisplayClass18_1.<Execute>b__1() in /_/src/dbup-core/Support/ScriptExecutor.cs:Zeile 146.
   bei DbUp.SqlServer.SqlScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action executeCommand) in /_/src/dbup-sqlserver/SqlScriptExecutor.cs:Zeile 51.
   bei DbUp.Support.ScriptExecutor.<>c__DisplayClass18_0.<Execute>b__0(Func`1 dbCommandFactory) in /_/src/dbup-core/Support/ScriptExecutor.cs:Zeile 144.
   bei DbUp.Engine.Transactions.NoTransactionStrategy.Execute(Action`1 action) in /_/src/dbup-core/Engine/Transactions/NoTransactionStrategy.cs:Zeile 14.
   bei DbUp.Engine.Transactions.DatabaseConnectionManager.ExecuteCommandsWithManagedConnection(Action`1 action) in /_/src/dbup-core/Engine/Transactions/DatabaseConnectionManager.cs:Zeile 103.
   bei DbUp.Support.ScriptExecutor.Execute(SqlScript script, IDictionary`2 variables) in /_/src/dbup-core/Support/ScriptExecutor.cs:Zeile 120.
ClientConnectionId:a7a7011f-4ea5-4785-888e-1c42ffa5b709
Fehlernummer (Error Number):2627,Status (State):1,Klasse (Class):14
Upgrade failed due to an unexpected exception:
System.Data.SqlClient.SqlException (0x80131904): Verletzung der PRIMARY KEY-Einschränkung "PK_Dataclass". Ein doppelter Schlüssel kann in das dbo.Dataclass-Objekt nicht eingefügt werden. Der doppelte Schlüsselwert ist (90112).
Verletzung der PRIMARY KEY-Einschränkung "PK_Helpertable". Ein doppelter Schlüssel kann in das dbo.Helpertable-Objekt nicht eingefügt werden. Der doppelte Schlüsselwert ist (991).
Die Anweisung wurde beendet.
Die Anweisung wurde beendet.
   bei System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   bei System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   bei System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   bei System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   bei System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   bei DbUp.Support.ScriptExecutor.ExecuteNonQuery(IDbCommand command) in /_/src/dbup-core/Support/ScriptExecutor.cs:Zeile 173.
   bei DbUp.Support.ScriptExecutor.<>c__DisplayClass18_1.<Execute>b__1() in /_/src/dbup-core/Support/ScriptExecutor.cs:Zeile 146.
   bei DbUp.SqlServer.SqlScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action executeCommand) in /_/src/dbup-sqlserver/SqlScriptExecutor.cs:Zeile 51.
   bei DbUp.Support.ScriptExecutor.<>c__DisplayClass18_0.<Execute>b__0(Func`1 dbCommandFactory) in /_/src/dbup-core/Support/ScriptExecutor.cs:Zeile 144.
   bei DbUp.Engine.Transactions.NoTransactionStrategy.Execute(Action`1 action) in /_/src/dbup-core/Engine/Transactions/NoTransactionStrategy.cs:Zeile 14.
   bei DbUp.Engine.Transactions.DatabaseConnectionManager.ExecuteCommandsWithManagedConnection(Action`1 action) in /_/src/dbup-core/Engine/Transactions/DatabaseConnectionManager.cs:Zeile 103.
   bei DbUp.Support.ScriptExecutor.Execute(SqlScript script, IDictionary`2 variables) in /_/src/dbup-core/Support/ScriptExecutor.cs:Zeile 159.
   bei DbUp.Engine.UpgradeEngine.PerformUpgrade() in /_/src/dbup-core/Engine/UpgradeEngine.cs:Zeile 85.
ClientConnectionId:a7a7011f-4ea5-4785-888e-1c42ffa5b709
Fehlernummer (Error Number):2627,Status (State):1,Klasse (Class):14
```

**Comment by Havagan** [comment]
The error, including the full `Exception` output, is logged in three places:

1. SqlScriptExecutor.ExecuteCommandsWithinExceptionHandler as a SqlException and is rethrown up to the...
2. ScriptExecutor.Execute as a DbException and is rethrown up to the...
3. UpgradeEngine.PerformUpgrade as an Exception.

Each step logs some script/block/line number details along with the full exception details.

### Discussion:

**Option:** A more refined fix might be to delegate all logging to the `UpgradeEngine` and have the `ScriptExecutor.Execute()` method return a `ExecuteScriptResult` that captures details the `UpgradeEngine` can use for logging.

**Option:** A quick and dirty change can be made to only log the database-specific script block/line number exception details at the `ScriptExecutor` level and let the `UpgradeEngine` then log the full Exception output. This results in less verbose output:

```
[SqlScriptExecutor] Script block number: 0; Block line 1; Procedure (NONE); Number 102; Message: Incorrect syntax near ';'.
[ScriptExecutor] Script block number: 0; Error Code: (NONE); Message: Incorrect syntax near ';'.
[UpgradeEngine] Upgrade failed due to an unexpected exception: Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ';'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DbUp.Support.ScriptExecutor.ExecuteNonQuery(IDbCommand command)
   at DbUp.Support.ScriptExecutor.<>c__DisplayClass20_2.<Execute>b__2()
   at DbUp.SqlServer.SqlScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action executeCommand)
   at DbUp.Support.ScriptExecutor.<>c__DisplayClass20_0.<Execute>b__0(Func`1 dbCommandFactory)
   at DbUp.Engine.Transactions.NoTransactionStrategy.Execute(Action`1 action)
   at DbUp.Engine.Transactions.DatabaseConnectionManager.ExecuteCommandsWithManagedConnection(Action`1 action)
   at DbUp.Support.ScriptExecutor.Execute(SqlScript script, IDictionary`2 variables)
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()
```
