### ISSUE TITLE
special characters issue

### ISSUE THREAD

**Issue by keren-steinberg** [DbUp/DbUp#722]
when running a script with the below, it fails

**Script:**
use my_schema;

/*!40000 ALTER TABLE `dict_reject_reasons_keren_test` DISABLE KEYS */;
INSERT INTO `test` VALUES (1383,'aaa\'s ') 
;
INSERT INTO `test` VALUES (1409,'xxx;') 
;
/*!40000 ALTER TABLE `dict_reject_reasons_keren_test` ENABLE KEYS */;

**Error**:
ERROR Script block number: 3; MySql error code: 0; Number 1064; Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''xxx' at line 2
Script block number: 3; MySql error code: 0; Number 1064; Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''xxx' at line 2
2023-08-23 12:00:25.4021 ERROR MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''xxx' at line 2
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at DbUp.Support.ScriptExecutor.ExecuteAndLogOutput(IDbCommand command) in /_/src/dbup-core/Support/ScriptExecutor.cs:line 178
   at DbUp.MySql.MySqlScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action executeCommand) in /_/src/dbup-mysql/MySqlScriptExecutor.cs:line 40

**Comment by mjauernig** [comment]
You have to quote the ```'``` inside ```'aaa's '```

Try 
```INSERT INTO test VALUES (1383,'aaa\'s ')```

See https://dev.mysql.com/doc/refman/8.0/en/string-literals.html

Or google for ```mysql string escape```

**Comment by keren-steinberg** [comment]
It is quoted as suggested, you only see it here when you edit the comment. This issue is happening when it is quoted as 'aaa\\'s\

**Comment by mjauernig** [comment]
Have you more then two columns in the table?

>  If you are adding values for **all** the columns of the table, you **do not need** to specify the column names in the SQL query. However, make sure the order of the values is in the same order as the columns in the table. Source:
[MySQL INSERT](https://www.w3schools.com/mysql/mysql_insert.asp)

Try this ```INSERT``` statement. Replace `columnname1` and `columnname2` by your column names.
```
/*!40000 ALTER TABLE dict_reject_reasons_keren_test DISABLE KEYS /;
INSERT INTO `test`(`columnname1`, `columname2`) VALUES (1383,'aaa\'s ')
;
INSERT INTO `test`(`columnname1`, `columname2`) VALUES (1409,'xxx;')
;
/!40000 ALTER TABLE dict_reject_reasons_keren_test ENABLE KEYS */;
```
