### ISSUE TITLE
Problem using mariadb 10.10+

### ISSUE THREAD

**Issue by pedroveiga99** [DbUp/DbUp#762]
I updated my mariadb from 10.5 to 10.10 and the DbUp.Engine.UpgradeEngine stopped working. After some research I found the problem is with MySql.Data as stated [here](https://stackoverflow.com/questions/74060289/mysqlconnection-open-system-invalidcastexception-object-cannot-be-cast-from-d). 

I leave here the error:
```
Database not found on server with connection string in settings: Object cannot be cast from DBNull to other types.
fail: DbUp.Engine.UpgradeEngine[0]
      Upgrade failed due to an unexpected exception:
      System.InvalidCastException: Object cannot be cast from DBNull to other types.
         at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
         at MySql.Data.MySqlClient.Driver.LoadCharacterSetsAsync(MySqlConnection connection, Boolean execAsync, CancellationToken cancellationToken)
         at MySql.Data.MySqlClient.Driver.ConfigureAsync(MySqlConnection connection, Boolean execAsync, CancellationToken cancellationToken)
         at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)
         at MySql.Data.MySqlClient.MySqlConnection.Open()
         at DbUp.Engine.Transactions.DatabaseConnectionManager.OperationStarting(IUpgradeLog upgradeLog, List`1 executedScripts) in /_/src/dbup-core/Engine/Transactions/DatabaseConnectionManager.cs:line 52
         at DbUp.Engine.UpgradeEngine.PerformUpgrade() in /_/src/dbup-core/Engine/UpgradeEngine.cs:line 66
```

Is there any change that can be done to make it work with more recent versions of mariadb?

**Comment by Alexander-Poganatz** [comment]
In a personal project I came up with a hack to extend DatabaseConnectionManager to use the MySqlConnector driver instead of MySql.Data since MySqlConnector seems to support both MySql and MariaDB
Custom class code:
```
internal class CustomMySQLConnector : DatabaseConnectionManager
    {

        public CustomMySQLConnector(string connectionString) : base(new DelegateConnectionFactory(l => new MySqlConnector.MySqlConnection(connectionString))) { }

        public override IEnumerable<string> SplitScriptIntoCommands(string scriptContents)
        {
            var mySQLConnectionManager = new MySqlConnectionManager(string.Empty);
            return mySQLConnectionManager.SplitScriptIntoCommands(scriptContents);
        }
    }
```

Program code:
```
var upgrader = DeployChanges.To
    .MySqlDatabase(new CustomMySQLConnector(connectionString))
   ...
```

**Comment by pedroveiga99** [comment]
@Alexander-Poganatz Is this really working for you? I tried and it still gives me an error
```
Database not found on server with connection string in settings: Object cannot be cast from DBNull to other types.
Unhandled exception. System.NotSupportedException: Character set 'utf8mb3' is not supported by .Net Framework.
   at MySql.Data.MySqlClient.CharSetMap.GetCharacterSet(DBVersion version, String charSetName)
   at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   at MySql.Data.MySqlClient.MySqlField.set_CharacterSetIndex(Int32 value)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteScalar()
   at MySqlExtensions.DatabaseExists(MySqlConnection connection, String databaseName)
   at MySqlExtensions.MySqlDatabase(SupportedDatabasesForEnsureDatabase supported, String connectionString, IUpgradeLog logger, Int32 timeout, String collation)
   at MySqlExtensions.MySqlDatabase(SupportedDatabasesForEnsureDatabase supported, String connectionString)
```

From what it seems to me it still uses MySql.Data

**Comment by droyad** [comment]
This seems to have been solved
