### ISSUE TITLE
error running script: "Variable argon2id has no value defined"

### ISSUE THREAD

**Issue by yecarri** [DbUp/DbUp#815]
I need to run a script that creates a user credential, for which I am using an argon2id generated hash. When I try to insert it using a merge statement, DbUp fails:

Script:

      create table test(string varchar(80) not null primary key);
      merge into test
      using (select '$argon2id$v=19$m=65536,t=3,p=4$MDAwMDAwMDE$W26CKR4lHdtUSJZ/9wzcG2JVJGRS5ICjEFy4JjtHdJQ' string ) source
      on test.string = source.string 
      when not matched then insert values(source.string);
      drop table test;

Result

      Upgrade failed due to an unexpected exception: System.InvalidOperationException: Variable argon2id has no value defined
         at DbUp.Engine.Preprocessors.VariableSubstitutionSqlParser.<>c__DisplayClass3_0.<ReplaceVariables>b__1(String name) in /_/src/dbup-core/Engine/Preprocessors/VariableSubstitutionSqlParser.cs:line 51
         at DbUp.Engine.Preprocessors.VariableSubstitutionSqlParser.ReadCustomStatement() in /_/src/dbup-core/Engine/Preprocessors/VariableSubstitutionSqlParser.cs:line 100
         at DbUp.Support.SqlParser.ReadQuotedString() in /_/src/dbup-core/Support/SqlParser.cs:line 303
         at DbUp.Support.SqlParser.Parse() in /_/src/dbup-core/Support/SqlParser.cs:line 71
         at DbUp.Engine.Preprocessors.VariableSubstitutionSqlParser.ReplaceVariables(IDictionary`2 variables) in /_/src/dbup-core/Engine/Preprocessors/VariableSubstitutionSqlParser.cs:line 57
         at DbUp.Engine.Preprocessors.VariableSubstitutionPreprocessor.Process(String contents) in /_/src/dbup-core/Engine/Preprocessors/VariableSubstitutionPreprocessor.cs:line 30
         at DbUp.Support.ScriptExecutor.PreprocessScriptContents(SqlScript script, IDictionary`2 variables) in /_/src/dbup-core/Support/ScriptExecutor.cs:line 103
         at DbUp.Support.ScriptExecutor.Execute(SqlScript script, IDictionary`2 variables) in /_/src/dbup-core/Support/ScriptExecutor.cs:line 117
         at DbUp.Engine.UpgradeEngine.PerformUpgrade() in /_/src/dbup-core/Engine/UpgradeEngine.cs:line 84
      System.InvalidOperationException: Variable argon2id has no value defined
         at DbUp.Engine.Preprocessors.VariableSubstitutionSqlParser.<>c__DisplayClass3_0.<ReplaceVariables>b__1(String name) in /_/src/dbup-core/Engine/Preprocessors/VariableSubstitutionSqlParser.cs:line 51
         at DbUp.Engine.Preprocessors.VariableSubstitutionSqlParser.ReadCustomStatement() in /_/src/dbup-core/Engine/Preprocessors/VariableSubstitutionSqlParser.cs:line 100
         at DbUp.Support.SqlParser.ReadQuotedString() in /_/src/dbup-core/Support/SqlParser.cs:line 303
         at DbUp.Support.SqlParser.Parse() in /_/src/dbup-core/Support/SqlParser.cs:line 71
         at DbUp.Engine.Preprocessors.VariableSubstitutionSqlParser.ReplaceVariables(IDictionary`2 variables) in /_/src/dbup-core/Engine/Preprocessors/VariableSubstitutionSqlParser.cs:line 57
         at DbUp.Engine.Preprocessors.VariableSubstitutionPreprocessor.Process(String contents) in /_/src/dbup-core/Engine/Preprocessors/VariableSubstitutionPreprocessor.cs:line 30
         at DbUp.Support.ScriptExecutor.PreprocessScriptContents(SqlScript script, IDictionary`2 variables) in /_/src/dbup-core/Support/ScriptExecutor.cs:line 103
         at DbUp.Support.ScriptExecutor.Execute(SqlScript script, IDictionary`2 variables) in /_/src/dbup-core/Support/ScriptExecutor.cs:line 117
         at DbUp.Engine.UpgradeEngine.PerformUpgrade() in /_/src/dbup-core/Engine/UpgradeEngine.cs:line 84

That happens because DbUp VariableSubstitutionPreprocessor is trying to parse whatever is enclosed into $ signs (like $var$) as a substitution variable.

Variable substitution should be disabled unless `WithVariables` is explicitly called.  It does not seem a good idea needing to call `WithVariablesDisabled` to explicitly disable variable substitution.

**Comment by BEQ25-coder** [comment]
I think the core issue here is really a syntax collision between two different systems using the same `$...$` pattern for completely different purposes.

In the SQL script, the Argon2 hash is just a literal string value:

```sql
'$argon2id$v=19$m=65536,t=3,p=4$...'
```

but before the script ever reaches the database, DbUp’s `VariableSubstitutionPreprocessor` scans the script text looking for DbUp variables in the form:

```text
$VariableName$
```

So `$argon2id$` gets interpreted as a DbUp substitution token instead of part of the hash itself, which is why it throws:

```text
Variable argon2id has no value defined
```

From what I can tell, this is less of a SQL/MERGE problem and more of a preprocessing/parser behaviour issue.

I can also understand why this was moved from “bug” to “enhancement”. Changing the default behaviour could potentially affect existing migrations that rely on substitution inside quoted strings, so a full default change may be risky for backwards compatibility.

A few ideas that might improve the situation without breaking existing users:

* Only enable variable substitution if `WithVariables(...)` is explicitly configured.
* Add an escape mechanism for literal `$` values.
* Allow configurable variable delimiters.
* Add a non-throwing mode where unresolved variables are left untouched.
* Improve documentation around `.WithVariablesDisabled()` for hashes, bcrypt, Argon2, PostgreSQL dollar quoting, etc.

At minimum, I think documenting this edge case clearly would help quite a lot, because Argon2/bcrypt style hashes are becoming increasingly common in seeded auth migrations.
