### ISSUE TITLE
Upgrade failed due to an unexpected exception: System.MissingMethodException: Method not found: 'DbUp.Engine.Output.IUpgradeLog DbUp.Builder.UpgradeConfiguration.get_Log()'.

### ISSUE THREAD

**Issue by yecarri** [DbUp/DbUp#816]
When I try to use a custom table for journal, I get `MissingMethodException`

    var upgrader = DeployChanges
    .To.PostgresqlDatabase(_ConnectionString)
    .JournalToSqlTable("public", "DbUp_SchemaVersions")
    .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly())
    .Build();            

This is the exception:

      Upgrade failed due to an unexpected exception: System.MissingMethodException: Method not found: 'DbUp.Engine.Output.IUpgradeLog DbUp.Builder.UpgradeConfiguration.get_Log()'.
         at SqlServerExtensions.<>c__DisplayClass5_1.<JournalToSqlTable>b__2()
         at DbUp.Support.TableJournal.DoesTableExist(Func`1 dbCommandFactory) in /_/src/dbup-core/Support/TableJournal.cs:line 192
         at DbUp.Support.TableJournal.<GetExecutedScripts>b__23_0(Func`1 dbCommandFactory) in /_/src/dbup-core/Support/TableJournal.cs:line 63
         at DbUp.Engine.Transactions.NoTransactionStrategy.Execute[T](Func`2 actionWithResult) in /_/src/dbup-core/Engine/Transactions/NoTransactionStrategy.cs:line 29
         at DbUp.Engine.Transactions.DatabaseConnectionManager.ExecuteCommandsWithManagedConnection[T](Func`2 actionWithResult) in /_/src/dbup-core/Engine/Transactions/DatabaseConnectionManager.cs:line 142
         at DbUp.Support.TableJournal.GetExecutedScripts() in /_/src/dbup-core/Support/TableJournal.cs:line 61
         at DbUp.Engine.UpgradeEngine.GetScriptsToExecuteInsideOperation() in /_/src/dbup-core/Engine/UpgradeEngine.cs:line 136
         at DbUp.Engine.UpgradeEngine.PerformUpgrade() in /_/src/dbup-core/Engine/UpgradeEngine.cs:line 70
      System.MissingMethodException: Method not found: 'DbUp.Engine.Output.IUpgradeLog DbUp.Builder.UpgradeConfiguration.get_Log()'.
         at SqlServerExtensions.<>c__DisplayClass5_1.<JournalToSqlTable>b__2()
         at DbUp.Support.TableJournal.DoesTableExist(Func`1 dbCommandFactory) in /_/src/dbup-core/Support/TableJournal.cs:line 192
         at DbUp.Support.TableJournal.<GetExecutedScripts>b__23_0(Func`1 dbCommandFactory) in /_/src/dbup-core/Support/TableJournal.cs:line 63
         at DbUp.Engine.Transactions.NoTransactionStrategy.Execute[T](Func`2 actionWithResult) in /_/src/dbup-core/Engine/Transactions/NoTransactionStrategy.cs:line 29
         at DbUp.Engine.Transactions.DatabaseConnectionManager.ExecuteCommandsWithManagedConnection[T](Func`2 actionWithResult) in /_/src/dbup-core/Engine/Transactions/DatabaseConnectionManager.cs:line 142
         at DbUp.Support.TableJournal.GetExecutedScripts() in /_/src/dbup-core/Support/TableJournal.cs:line 61
         at DbUp.Engine.UpgradeEngine.GetScriptsToExecuteInsideOperation() in /_/src/dbup-core/Engine/UpgradeEngine.cs:line 136
         at DbUp.Engine.UpgradeEngine.PerformUpgrade() in /_/src/dbup-core/Engine/UpgradeEngine.cs:line 70

**Comment by devlux** [comment]
I think it's the same issue as mentioned in https://github.com/DbUp/DbUp/issues/803: I had to install the latest prerelease of `dbup-postgresql` to get rid of the issue.
